name: Preprocessing Telco Data

on:
  push:
    branches: ["main"]  
    paths:
      - '**.py'
      - 'telco_raw/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.7

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn

    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_Cikal-Firdansyah-Ramadhan.py

    - name: Commit and Push Processed Data
      run: |
        git config user.name "cikal-actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://cikal:${{ secrets.GH_TOKEN }}@github.com/cikalfirdansyah/Eksperimen_SML_Cikal-Firdansyah-Ramadhan.git
        git add preprocessing/telco_preprocessing/telco_preprocessing.csv
        git commit -m "Update preprocessed data via workflow"
        git push origin main
      continue-on-error: true