name: Preprocessing Telco Data

on:
  push:
    branches: ["main"]  
    paths:
      - '**.py'
      - 'telco_raw/**'
      - '.github/workflows/**'

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.7

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn mlflow==2.19.0

    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_Cikal_Firdansyah.py

    - name: Commit and Push Processed Data
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add preprocessing/telco_preprocessing/telco_preprocessing.csv
        git commit -m "Update preprocessed data via workflow"
        git push
      continue-on-error: true